immobile/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('imovel.urls')),
    path('usuario/', include('usuario.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

imovel/urls.py
from django.urls import path

from imovel import views

urlpatterns = [
    path('home/', views.home, name='home'),
    path('perfil-imoveis/', views.perfil_imoveis, name='perfil_imoveis'),
    path('item-imovel/<int:id_imovel>', views.item_imovel, name='item_imovel'),
    path('adicionar-imovel/', views.AdicionarImovelView.as_view(), name='adicionar_imovel'),
    path('remover-imovel/<int:imovel_id>', views.remover_imovel, name='remover_imovel'),
    path('item-imovel/<int:id>/editar', views.editar_imovel, name='editar_imovel'),
    path('add-proprietario/<int:id>', views.add_proprietario, name='add_proprietario'),
]

imovel/models.py
from django.db import models

from usuario.models import Perfil


class Imovel(models.Model):
    nome = models.CharField(max_length=50)
    descricao = models.TextField(max_length=100)
    cep = models.CharField(max_length=10)
    numero = models.CharField(max_length=30)
    rua = models.CharField(max_length=50)
    bairro = models.CharField(max_length=50)
    cidade = models.CharField(max_length=50)
    estado = models.CharField(max_length=50)
    perfis = models.ManyToManyField(Perfil, related_name='imoveis')
    imagem = models.FileField(upload_to='imovel/', default='imovel/default.jpg')

imovel/forms.py
from django import forms

from imovel.models import Imovel


class AdicionarImovelForm(forms.ModelForm):
    nome = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'nome'}))

    descricao = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'descrição'}))
    cep = forms.CharField(max_length=10, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'cep'}))
    numero = forms.CharField(max_length=30, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'numero'}))
    rua = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'rua'}))
    bairro = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'bairro'}))
    cidade = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'cidade'}))
    estado = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'estado'}))

    class Meta:
        model = Imovel
        exclude = ['perfis']


class AddPerfilForm(forms.ModelForm):

    class Meta:
        model = Imovel
        fields = ['perfis']

imovel/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.views.generic.base import View

from imovel.forms import *
from imovel.models import Imovel
from usuario.models import Perfil


@login_required
def home(request):
    imoveis = Imovel.objects.all()
    return render(request, 'home.html', {'imoveis': imoveis})


@login_required
def item_imovel(request, id_imovel):
    imovel = Imovel.objects.get(id=id_imovel)
    return render(request, 'item_imovel.html', {'imovel': imovel})


def perfil_imoveis(request):
    perfil_logado = get_perfil_logado(request)
    imoveis = perfil_logado.imoveis.all()
    return render(request, 'perfil_imoveis.html', {'imoveis': imoveis})


class AdicionarImovelView(View):
    template_post = 'adicionar_imovel.html'

    def get(self, request):
        form = AdicionarImovelForm()
        return render(request, self.template_post, {'form': form})

    def post(self, request):
        adicionar_imovelForm = AdicionarImovelForm(request.POST, request.FILES)
        perfil_logado = get_perfil_logado(request)

        if adicionar_imovelForm.is_valid():
            imovel = adicionar_imovelForm.save()
            imovel.perfis.add(perfil_logado)
            imovel.save()
            return redirect('home')

        return render(request, self.template_post, {'form': adicionar_imovelForm})


def editar_imovel(request, id):
    imovel = Imovel.objects.get(id=id)
    if request.method == 'GET':
        form = AdicionarImovelForm(instance=imovel)
        return render(request, 'adicionar_imovel.html', {'form': form})

    else:
        adicionar_imovelForm = AdicionarImovelForm(request.POST, request.FILES, instance=imovel)

        if adicionar_imovelForm.is_valid():
            adicionar_imovelForm.save()

            return redirect('item_imovel', id)

        return render(request, 'adicionar_imovel.html', {'form': adicionar_imovelForm})


def get_perfil_logado(request):
    return request.user.perfil


def remover_imovel(request, imovel_id):
    imovel = Imovel.objects.get(id=imovel_id)
    imovel.delete()
    return redirect('perfil_imoveis')


def add_proprietario(request, id):
    imovel = Imovel.objects.get(id=id)
    perfil_list = Perfil.objects.exclude(id__in=imovel.perfis.all())

    if request.method == 'GET':
        form = AddPerfilForm()
        return render(request, 'add_proprietario.html', {'form': form, 'perfil_list': perfil_list})

    else:
        form = AddPerfilForm(request.POST)

        if form.is_valid():
            imovel.perfis.add(form.cleaned_data['perfis'][0])
            return redirect('item_imovel', id)

        return render(request, 'add_proprietario.html', {'form': form, 'perfil_list': perfil_list})

imovel/templates/add_proprietario.html
{% extends "base_imovel.html" %}
{% load static %}
{% block body %}

<div class="container container mt-4 mb-5">
  <h3 class="display-4 text-center" style="margin-top:3.5rem"> Adicionar Proprietario </h3>
  <hr class="bg-dark mb-4 w-25">
  <div class="row" style="padding:20px">
    <div class="col-sm-3"></div>
    <div class="col-sm-6">

      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}

        <select class="form-control form-control-lg" name="perfis" id="id_perfis">
          <option>-- Selecione um perfil --</option>
          {% for perfil in perfil_list %}
          <option value="{{ perfil.id }}">{{ perfil }}</option>
          {% endfor %}
        </select>

        <div class="form-group">
          <button class="btn btn-warning btn-block" type="submit">Adicionar</button>
        </div>

        {% if form.errors %}
        <div class="alert alert-danger">
          <button aria-hidden="true" class="close"
                  data-dismiss="alert" type="button">
          </button>
          {{ form.errors }}
        </div>
        {% endif %}

      </form>
    </div>
  </div>
</div>

{% endblock %}

imovel/templates/adicionar_imovel.html
{% extends "base_imovel.html" %}
{% block body %}

<div class="container container mt-4 mb-5">

  {% if form.instance.id %}
  <h3 class="display-4 text-center"> Editar </h3>
  {% else %}
  <h3 class="display-4 text-center"> Adicionar </h3>
  {% endif %}

  <hr class="bg-dark mb-4 w-25">
  <div class="row" style="padding:20px">
    <div class="col-sm-3"></div>
    <div class="col-sm-6">
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}

        {% for field in form %}
        <div class="form-group">
          {{ field }}
        </div>
        {% endfor %}

        <div class="form-group">
          <button class="btn btn-warning btn-block" type="submit">Salvar</button>
        </div>

        {% if form.errors %}
        <div class="alert alert-danger">
          <button aria-hidden="true" class="close"
                  data-dismiss="alert" type="button">
          </button>
          {{ form.errors }}
        </div>
        {% endif %}

      </form>
    </div>
  </div>
</div>

{% endblock %}

imovel/templates/base_imovel.html
<!DOCTYPE html>

{% load static %}

<html lang="pt">
<head>
  <meta charset="UTF-8">
  <title>Immobile</title>
  <link href="{% static 'bootstrap\css\bootstrap.min.css' %}" rel="stylesheet" id="bootstrap-css">
  <link href="{% static 'imovel\css\style.css' %}" rel="stylesheet">
  <script src="{% static 'bootstrap\js\bootstrap.min.js' %}"></script>
</head>
<body>
<!-- Navigation -->
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
  <div class="container">
    <a class="navbar-brand text-white" href="{% url 'home' %}">IMOVEIS</a>
    <button aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation"
            class="navbar-toggler"
            data-target="#navbarsExampleDefault" data-toggle="collapse" type="button">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link text-white" href="{% url 'adicionar_imovel' %}">Adicionar</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white" href="{% url 'perfil_imoveis' %}">Meus imoveis</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white" href="{% url 'logout' %}">Logout</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
<!-- Navigation -->

<!-- Page Content -->
{% block body %}
{% endblock %}
<!-- Page Content -->

</body>
</html>

imovel/templates/home.html
{% extends "base_imovel.html" %}
{% load static %}
{% block body %}

<!-- Card -->
<div class="container container mt-4 mb-5 h-100">
  <h3 class="display-4 text-center"> Imoveis </h3>
  <hr class="bg-dark mb-4 w-25">
  <div class="row h-100">
    {% if imoveis.count != 0 %}

    {% for imovel in imoveis %}
    <div class="col-md-4">
      <div class="card mb-4">
        <img class="card-img-top" src="{{ MEDIA_URL }}{{ imovel.imagem.url }}" style="height: 200px;"
             alt="Card image cap">
        <div class="card-block p-3">
          <h4 class="card-title">{{ imovel.nome }}</h4>
          <p class="card-text">{{ imovel.descricao }}</p>
          <a href="{% url 'item_imovel' imovel.id %}" class="btn btn-primary rounded-0 mb-2">Detalhes</a>
        </div>
      </div>
    </div>
    {% endfor %}
    {% else %}

    <div class="col-md-12 d-flex align-items-center">
      <h1 class="text-center w-100">
        Não existe imoveis cadastrados
      </h1>
    </div>
    {% endif %}
    <!-- Card -->
  </div>
</div>

{% endblock %}

imovel/templates/item_imovel.html
{% extends "base_imovel.html" %}
{% load static %}

{% block body %}
<div class="container">

  <div class="row">

    <!-- .col-lg-3 -->
    <div class="col-lg-2"></div>

    <div class="col-lg-8">
      <div class="card mt-4">
        <img class="card-img-top img-fluid" src="{{ MEDIA_URL }}{{ imovel.imagem.url }}" alt="">
        <div class="card-body">
          <!-- Nome -->
          <h3 class="card-title">{{ imovel.nome }}</h3>

          <!-- Contato -->
          <h5>Contato(s): </h5>
          {% for perfil in imovel.perfis.all %}
          <b>{{ perfil.nome }} - </b><a href="https://web.whatsapp.com/">Telefone: {{ perfil.telefone }}</a>
          <a class="m-5">Email: {{ perfil.email }}</a>
          <br>
          {% endfor %}

          <!-- Descricao -->
          <h5 class="pt-4">Descrição do imóvel</h5>
          <div class="w-100 pl-3 pb-3 mh-75">
            <p class="card-text">{{ imovel.descricao }}</p>
          </div>

          <span class="text-warning">&#9733; &#9733; &#9733; &#9733; &#9734;</span>
          4.0 stars
        </div>
      </div>
      <!-- /.card -->

      <div class="card card-outline-secondary my-4">
        <div class="card-header">
          <h5>Endereço</h5>
        </div>
        <div class="card-body">

          <div class="row" style="min-height: 150px;">
            <row class="d-flex justify-content-around" style="min-width: 100%;">
              <div class="col" style="min-width:50%;">
                <p><b class="pl-3">Rua: </b>{{ imovel.rua }}</p>
              </div>
              <div class="col">
                <p><b class="pl-3">Nº: </b>{{ imovel.numero }}</p>
              </div>
              <div class="col">
                <p><b class="pl-3">CEP: </b>{{ imovel.cep }}</p>
              </div>
            </row>
            <row class="d-flex justify-content-around" style="min-width: 100%;">
              <div class="col" style="min-width:50%;">
                <p><b class="pl-3">Bairro: </b>{{ imovel.bairro }}</p>
              </div>
              <div class="col">
                <p><b class="pl-3">Cidade: </b>{{ imovel.cidade }}</p>
              </div>
              <div class="col">
                <p><b class="pl-3">UF: </b>{{ imovel.estado }}</p>
              </div>
            </row>
          </div>

          <hr>
          {% if request.user.perfil in imovel.perfis.all %}
          <div class="d-flex justify-content-around">
            <a href="{% url 'remover_imovel' imovel.id %}"
               class="btn btn-danger rounded-0 mb-2">Remover</a>
            <a href="{% url 'editar_imovel' imovel.id %}" class="btn btn-primary rounded-0 mb-2">Editar informações</a>
            <a href="{% url 'add_proprietario' imovel.id %}" class="btn btn-primary rounded-0 mb-2">Adicionar
              proprietario</a>
          </div>
          {% endif %}
        </div>
      </div>
      <!-- /.card -->

    </div>
    <!-- /.col-lg-8 -->
  </div>
  <!-- /.row -->
</div>
<!-- /.container -->

<!-- Footer -->
<footer class="py-5 bg-dark">
  <div class="container">
    <p class="m-0 text-center text-white">Copyright &copy; Immobile Website 2019</p>
  </div>
</footer>
<!-- Footer -->

{% endblock %}

imovel/templates/perfil_imoveis.html
{% extends "base_imovel.html" %}
{% load static %}
{% block body %}


<!-- Card -->
<div class="container container mt-4 mb-5">
    <h3 class="display-4 text-center"> Meus imoveis </h3>
    <hr class="bg-dark mb-4 w-25">
    <div class="row">
        {% for imovel in imoveis %}
        <div class="col-md-4">
            <div class="card mb-4">
                <img class="card-img-top" src="{{ MEDIA_URL }}{{ imovel.imagem.url }}" style="height: 200px;"
                     alt="Card image cap">
                <div class="card-block p-3">
                    <h4 class="card-title">{{ imovel.nome }}</h4>
                    <p class="card-text">{{ imovel.descricao }}</p>
                    <a href="{% url 'item_imovel' imovel.id %}" class="btn btn-primary rounded-0 mb-2">Detalhes</a>
                </div>
            </div>
        </div>
        {% endfor %}
<!-- Card -->
    </div>
</div>

{% endblock %}